swagger: '2.0'
info:
  version: 0.0.0
  title: 'DOI Service'
host: 0.0.0.0:8080
schemes:
  - https
tags:
  - name: DOI
securityDefinitions:
  Bearer:
    type: apiKey
    in: header
    name: Authorization
paths:
  /health:
    get:
      security: []
      summary: healthcheck
      operationId: healthcheck
      x-scala-package: healthcheck
      description: Ensure the service is responding to requests.
      responses:
        200:
          description: Success
  /organizations/{organizationId}/datasets/{datasetId}/doi:
    get:
      summary: retrieve latest DOI information for the dataset
      security:
        - Bearer: []
      operationId: getLatestDoi
      x-scala-package: doi
      produces:
        - application/json
      parameters:
        - name: organizationId
          in: path
          description: organization id
          required: true
          type: integer
          format: int32
        - name: datasetId
          in: path
          description: dataset id
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: Success
          schema:
            type: object
            x-scala-type: com.pennsieve.doi.models.DoiDTO
        401:
          description: Unauthorized
        403:
          description: Forbidden
          schema:
            type: string
        404:
          description: resource not found
          schema:
            type: string
        500:
          description: Internal error
          schema:
            type: string
    post:
      summary: create a Draft DOI for a dataset
      security:
        - Bearer: []
      operationId: createDraftDoi
      x-scala-package: doi
      produces:
        - application/json
      parameters:
        - name: organizationId
          in: path
          description: organization id
          required: true
          type: integer
          format: int32
        - name: datasetId
          in: path
          description: dataset id
          required: true
          type: integer
          format: int32
        - name: body
          in: body
          description: dataset metadata
          required: true
          schema:
            $ref: '#/definitions/CreateDraftDoiRequest'
      responses:
        201:
          description: Created
          schema:
            type: object
            x-scala-type: com.pennsieve.doi.models.DoiDTO
        400:
          description: Bad Request
          schema:
            type: string
        401:
          description: Unauthorized
        403:
          description: Forbidden
          schema:
            type: string
        500:
          description: Internal error
          schema:
            type: string
  /doi/{doi}:
    get:
      summary: retrieve DOI information
      security:
        - Bearer: []
      operationId: getDoi
      x-scala-package: doi
      produces:
        - application/json
      parameters:
        - name: doi
          in: path
          description: DOI
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            type: object
            x-scala-type: com.pennsieve.doi.models.DoiDTO
        401:
          description: Unauthorized
        403:
          description: Forbidden
          schema:
            type: string
        404:
          description: resource not found
          schema:
            type: string
        500:
          description: Internal error
          schema:
            type: string
  /doi/{doi}/publish:
    put:
      summary: mark DOI as Findable
      security:
        - Bearer: []
      operationId: publishDoi
      x-scala-package: doi
      produces:
        - application/json
      parameters:
        - name: doi
          in: path
          description: DOI
          required: true
          type: string
        - name: body
          in: body
          description: dataset metadata
          required: true
          schema:
            $ref: '#/definitions/PublishDoiRequest'
      responses:
        200:
          description: Success
          schema:
            type: object
            x-scala-type: com.pennsieve.doi.models.DoiDTO
        400:
          description: Bad Request
          schema:
            type: string
        401:
          description: Unauthorized
        403:
          description: Forbidden
          schema:
            type: string
        404:
          description: resource not found
          schema:
            type: string
        500:
          description: Internal error
          schema:
            type: string

  /doi/{doi}/hide:
    put:
      summary: mark a previously Findable DOI as Registered
      security:
        - Bearer: []
      operationId: hideDoi
      x-scala-package: doi
      produces:
        - application/json
      parameters:
        - name: doi
          in: path
          description: DOI
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            type: object
            x-scala-type: com.pennsieve.doi.models.DoiDTO
        400:
          description: Bad Request
          schema:
            type: string
        401:
          description: Unauthorized
        403:
          description: Forbidden
          schema:
            type: string
        404:
          description: resource not found
          schema:
            type: string
        500:
          description: Internal error
          schema:
            type: string


  /doi/{doi}/revise:
    put:
      summary: update a DOI
      security:
        - Bearer: []
      operationId: reviseDoi
      x-scala-package: doi
      produces:
        - application/json
      parameters:
        - name: doi
          in: path
          description: DOI
          required: true
          type: string
        - name: body
          in: body
          description: dataset metadata
          required: true
          schema:
            $ref: '#/definitions/ReviseDoiRequest'
      responses:
        200:
          description: Success
          schema:
            type: object
            x-scala-type: com.pennsieve.doi.models.DoiDTO
        400:
          description: Bad Request
          schema:
            type: string
        401:
          description: Unauthorized
        403:
          description: Forbidden
          schema:
            type: string
        404:
          description: resource not found
          schema:
            type: string
        500:
          description: Internal error
          schema:
            type: string

  /citations:
    get:
      summary: get citation for a DOI (does not have to be a Blackfynn DOI)
      security:
        - Bearer: []
      operationId: getCitations
      x-scala-package: doi
      produces:
        - application/json
      parameters:
        - name: dois
          in: query
          description: DOI
          required: true
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        207:
          schema:
            type: array
            items:
              type: object
              $ref: '#/definitions/CitationDTO'
        500:
          description: Internal error
          schema:
            type: string

definitions:
  CreateDraftDoiRequest:
    type: object
    properties:
      title:
        type: string
      creators:
        type: array
        items:
          type: object
          $ref: '#/definitions/CreatorDTO'
      publicationYear:
        type: integer
        format: int32
      suffix:
        type: string
      version:
        type: integer
        format: int32
      owner:
        type: object
        $ref: '#/definitions/CreatorDTO'
      description:
        type: string
      licenses:
        type: array
        items:
          type: object
          $ref: '#/definitions/LicenseDTO'

  ReviseDoiRequest:
    type: object
    required:
      - title
      - creators
    properties:
      title:
        type: string
      creators:
        type: array
        items:
          type: object
          $ref: '#/definitions/CreatorDTO'
      owner:
        type: object
        $ref: '#/definitions/CreatorDTO'
      version:
        type: integer
        format: int32
      description:
        type: string
      licenses:
        type: array
        items:
          type: object
          $ref: '#/definitions/LicenseDTO'
      collections:
        type: array
        items:
          type: object
          $ref: '#/definitions/CollectionDTO'
      externalPublications:
        type: array
        items:
          type: object
          $ref: '#/definitions/ExternalPublicationDTO'

  PublishDoiRequest:
    type: object
    required:
      - title
      - creators
      - publicationYear
      - url
    properties:
      title:
        type: string
      creators:
        type: array
        items:
          type: object
          $ref: '#/definitions/CreatorDTO'
      publicationYear:
        type: integer
        format: int32
      url:
        type: string
      owner:
        type: object
        $ref: '#/definitions/CreatorDTO'
      version:
        type: integer
        format: int32
      description:
        type: string
      licenses:
        type: array
        items:
          type: object
          $ref: '#/definitions/LicenseDTO'
      collections:
        type: array
        items:
          type: object
          $ref: '#/definitions/CollectionDTO'
      externalPublications:
        type: array
        items:
          type: object
          $ref: '#/definitions/ExternalPublicationDTO'

  CreatorDTO:
    type: object
    required:
      - firstName
      - lastName
    properties:
      firstName:
        type: string
      lastName:
        type: string
      middleInitial:
        type: string
      orcid:
        type: string

  LicenseDTO:
    type: object
    required:
    - license
    - licenseUri
    properties:
      license:
        type: string
      licenseUri:
        type: string

  CollectionDTO:
    type: object
    required:
    - name
    - id
    properties:
      name:
        type: string
      id:
        type: integer
        format: int32

  ExternalPublicationDTO:
    type: object
    required:
    - doi
    properties:
      doi:
        type: string
      relationshipType:
        type: string

  CitationDTO:
    type: object
    required:
     - status
     - doi
    properties:
      status:
        type: integer
        format: int32
        description: status code of individual DOI lookup
        enum:
          - 200
          - 404
      doi:
        type: string
      citation:
        type: string
